# You can remove the 'version' line to get rid of the warning
version: '3.8'

services:
  ops-agent:
    build:
      context: ./ops-agent
    ports:
      # We map port 8000 on our Windows machine to port 8000 inside the container.
      # This single port will serve BOTH the website and the API.
      - "8000:8000"
    volumes:
      # This shares our Python code with the container
      - ./ops-agent:/app
      # This shares our SOPs with the container
      - ./sops:/app/sops
      # This shares our new frontend code with the container
      - ./frontend:/app/static
    env_file:
      - .env
    # We are REMOVING stdin_open and tty because we will be using a web UI
    # for approval, not the command line input.