version: '3.8'
services:
  ops-agent:
    build:
      context: ./ops-agent
    ports:
      - "8001:8000"
    volumes:
      - ./ops-agent:/app
      - ./sops:/app/sops
    env_file:
      - .env

# Add these two lines
stdin_open: true  # This keeps the standard input open
tty: true         # This allocates a pseudo-TTY (a terminal)