# You can remove this line to fix the warning
version: '3.8'

services:
  ops-agent:
    build:
      context: ./ops-agent
    ports:
      - "8001:8001"  # <-- CHANGED: API will now be on 8001
      - "8000:8000"  # <-- NEW: Frontend will be on 8000
    volumes:
      - ./ops-agent:/app
      - ./sops:/app/sops
      - ./frontend:/app/static # <-- NEW: Mount the frontend folder
    env_file:
      - .env
    stdin_open: true
    tty: true