# You can remove this line to fix the warning
version: '3.8'

services:
  # This is the service name
  ops-agent:
    # All of the following lines are properties of 'ops-agent'
    # and must be indented further than 'ops-agent:'.
    build:
      context: ./ops-agent
    ports:
      - "8001:8000"
    volumes:
      - ./ops-agent:/app
      - ./sops:/app/sops
    env_file:
      - .env
    stdin_open: true  # Correctly indented under ops-agent
    tty: true         # Correctly indented under ops-agent